######################################################################
# Automatically generated by qmake (3.0) Sat May 31 12:57:41 2014
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

QT += widgets

CONFIG += c++11

# Input
HEADERS += playing_field.h playing_field_widget.h
SOURCES += main.cpp playing_field.cpp playing_field_widget.cpp
