######################################################################
# Automatically generated by qmake (3.0) Sat May 31 12:57:41 2014
######################################################################

TEMPLATE = app
TARGET = Tic-Tac-Toe-Server
INCLUDEPATH += .

QT += widgets
QT += network

CONFIG += c++11

DESTDIR = /Users/Alexander/Projects/tic-tac-toe/build

# Input
HEADERS += server.h
           
SOURCES += main.cpp \
           server.cpp
            